import json
from config import gemini_client

def synthesize_rag_response(query: str, retrieved_chunks: list[dict]) -> dict:
    """
    Synthesizes a response using Gemini based on the retrieved context documents.
    Consolidates response generation and confidence evaluation in a single API call.
    """
    if not retrieved_chunks:
        return {
            "answer": (
                "I could not find any specific research documents or clinical guidelines in my local database "
                "to answer your question. However, based on general medical knowledge, here is some information:\n\n"
                "Please upload relevant clinical guidelines to search them accurately."
            ),
            "confidence": 40,
            "rationale": "No relevant local documents found in Qdrant."
        }
        
    # Construct context text
    context_str = ""
    for idx, chunk in enumerate(retrieved_chunks):
        context_str += f"--- Document Chunk {idx+1} (Source: {chunk['source_file']}) ---\n"
        context_str += chunk['text'] + "\n\n"
        
    system_instruction = (
        "You are an expert clinical RAG assistant. Your job is to answer the user's medical query "
        "using ONLY the provided Document Chunks. For each factual claim you make, cite the source "
        "document by appending '[Source: document_name]' in the text.\n\n"
        "If the provided Document Chunks do not contain enough information to answer the query, "
        "plainly state that you cannot find a complete answer in the reference documents, but "
        "provide general medical context based on the chunks.\n\n"
        "Format your output in professional markdown with clear bullet points and bold headers.\n\n"
        "You must return your output as a JSON object with the following keys:\n"
        "- 'answer': The text containing the clinical response.\n"
        "- 'confidence_score': An integer (0 to 100) reflecting how certain and safe your response is based on the chunks.\n"
        "- 'rationale': A one-sentence explanation of why you assigned this confidence score."
    )
    
    try:
        response = gemini_client.models.generate_content(
            model="gemini-2.5-flash",
            contents=f"User Query: {query}\n\n{context_str}",
            config={
                "system_instruction": system_instruction,
                "response_mime_type": "application/json",
                "temperature": 0.1,
            }
        )
        result = json.loads(response.text.strip())
        return {
            "answer": result.get("answer", ""),
            "confidence": result.get("confidence_score", 90),
            "rationale": result.get("rationale", "Grounded clinical RAG extraction.")
        }
    except Exception as e:
        print(f"[RAG Synthesis] Error generating response: {e}")
        return {
            "answer": "Error synthesizing response from reference documents.",
            "confidence": 30,
            "rationale": f"API synthesis failed: {str(e)}"
        }

def synthesize_final_response(route: str, query: str, agent_output: dict) -> dict:
    """
    Combines agent outputs, structures results, and appends legal disclaimers.
    Optimized to use ZERO extra API calls (all safety and confidence evaluations
    are handled inline by the specialist sub-agents).
    """
    print(f"[Response Synthesizer] Synthesizing final response for route: {route}")
    
    final_answer = ""
    confidence = 85
    rationale = ""
    citations = []
    agent_name = ""
    
    # Process Route Specific Output
    if route == "VISION":
        final_answer = agent_output.get("analysis", "")
        confidence = agent_output.get("confidence", 85)
        rationale = agent_output.get("rationale", "")
        agent_name = "Vision Agent"
    elif route == "RAG":
        chunks = agent_output.get("retrieved_chunks", [])
        rag_result = synthesize_rag_response(query, chunks)
        final_answer = rag_result.get("answer", "")
        confidence = rag_result.get("confidence", 85)
        rationale = rag_result.get("rationale", "")
        citations = [
            {"source_file": chunk["source_file"], "score": chunk["score"]}
            for chunk in chunks
        ]
        agent_name = "RAG Agent"
    else: # CHAT
        final_answer = agent_output.get("response", "")
        confidence = agent_output.get("confidence", 85)
        rationale = agent_output.get("rationale", "")
        agent_name = "Chat Agent"
        
    # Append Safety Disclaimer at the bottom
    disclaimer = (
        "\n\n---\n"
        "*Disclaimer: This response is generated by an AI assistant for research and educational purposes. "
        "It is not a substitute for professional medical advice, diagnosis, or treatment. "
        "Always consult a licensed healthcare professional for clinical concerns.*"
    )
    final_answer += disclaimer
    
    return {
        "success": True,
        "final_answer": final_answer,
        "confidence": confidence,
        "rationale": rationale,
        "citations": citations,
        "agent": agent_name
    }
